### ISSUE TITLE
Provide media meta data info 

### ISSUE THREAD

**Issue by markst** [sommye-ctr/video_cast#4]
I notice this is a clone of the `flutter_video_cast` package which isn't active. 

I wonder about bringing in the changes I've made here to allow for providing meta data:
https://github.com/PalaTeam/flutter_video_cast/pull/22

**Comment by sommye-ctr** [comment]
This fork already supports some metadata to be passed, what other metadata needs to be passed?

PS. sorry for the late reply (not sure if you still need it or not)
